services:
  tensortrust:
    build:
      context: . 
      dockerfile: Dockerfile
    image: agentbeats/tensortrust:v1.0.0

    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SCENARIO_ROOT=/workspace

    extra_hosts:
      - "host.docker.internal:host-gateway" # to let linux systems work; don't affect windows/macOS

    ports:
      # TODO: only map necessary agent ports
      # TODO: make port read from env/arg
      # TODO: make it configurable for more mcps
      - "9010-9099:9010-9099" # agents
      - "9000:9000" # backend
      - "9001:9001" # backend mcp

    # only mount scenario and requirements;
    # IMPORTANT NOTE: entrypoint.sh will be copied into container 
    # (through Dockerfile) instead of mounted, since it will be replaced 
    # CRLF->LF in the container, which shouldn't affect the host
    volumes:
      - ./scenario:/workspace/scenario
      - ./requirements.txt:/workspace/requirements.txt:ro

    # TODO: not considering healthcheck for now
    # healthcheck:
    #   test: ["CMD-SHELL", "curl -fs http://localhost:9010/health || exit 1"]
    #   interval: 10s
    #   retries: 5
